import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Home/Layout";
import profile from "../../public/images/lanrem.png";
import { Text } from "@/components/Text";
import Link from "next/link";
import { motion } from "framer-motion";
import HireBtn from "@/components/HireBtn";
const inter = Inter({ subsets: ["latin"] });
import light from "../../public/images/svgs/light.svg";
import useTheme from "@/components/hooks/useTheme";
import PageTransition from "@/components/PageTransition";

const Motion = motion(Link);

export default function Home() {
  const { theme } = useTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTransition />
      <main className="flex items-center text-black w-full min-h-screen lg:pb-0">
        <Layout className="!pt-0 md:pt-16 sm:pt-8 sm:px-0 lg:!pb-4">
          <div className="w-full flex text-light lg:flex-col dark:text-light gap-4 items-center justify-between sm:pt-8">
            <div className="w-1/2 sm:flex sm:justify-center sm:items-center  sm:w-full">
              <Image
                src={profile}
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                priority
                alt="codephoto"
                className="w-full h-auto lg:w-9/12 lg:h-1/2 md:inline-block sm:inline-block"
              />
            </div>
            <div className="w-1/2 flex flex-col item-center self-center lg:w-full lg:text-center lg:px-4">
              <h1></h1>
              <Text
                text="Turning Vision Into Reality With Code And Design."
                className="!text-left !text-6xl xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Cv2.pdf"
                  target={"_blank"}
                  download={true}
                  className={`flex items-center bg-black text-white p-2.5 px-6 md:p-2 md:px-4 md:text-base rounded-lg text-lg font-semibold hover:bg-white hover:text-black border border-solid border-transparent hover:border-black ${
                    theme === "light"
                      ? "bg-white text-dark"
                      : "bg-dark text-white border border-solid border-white"
                  }`}
                >
                  Resume
                </Link>
                <Motion
                  href="mailto:lutfiyar888lutfiyar@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize  p-2.5 px-6 md:p-2 md:px-4 md:text-base rounded-lg text-white bg-[rgba(253,29,29,1)] border border-solid border-white"
                  whileHover={{
                    backgroundColor: [
                      "rgba(253,29,29,1)",
                      "rgba(131,58,180,1)",
                      "#121212",
                      "rgba(252,176,69,1)",
                      "rgba(131,58,180,1)",
                      "#121212",
                    ],
                    border: "none",
                    color: "white",
                    transition: { duration: 1, repeat: Infinity },
                  }}
                >
                  Contact
                </Motion>
              </div>
            </div>
          </div>
        </Layout>
        <HireBtn />
        <div className="absolute right-8 bottom-56 inline-block w-24 lg:hidden">
          <Image src={light} alt="altimage" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
